# Generated by Django 5.1.6 on 2025-02-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='afrad',
            name='aks',
            field=models.ImageField(blank=True, null=True, upload_to='aks_afrad/'),
        ),
    ]
